name: lambdahs

executables:

  derive:
    main: Derive.hs

  zebra:
    default-extensions:
      - TypeApplications
    main: Zebra.hs

tests:
  test:
    default-extensions:
      - OverloadedStrings
      - TypeFamilies
    main: Main.lhs

dependencies:
  - base
